#!/usr/bin/env python3
"""Generate docs/loc_audit.md from git numstat data."""

import argparse
import os
import subprocess
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


@dataclass
class Row:
    path: str
    added: int
    deleted: int


@dataclass
class RepoSpec:
    name: str
    path: str
    base: str = "origin/master"
    paths: tuple[str, ...] = ()
    exclude: tuple[str, ...] = ()


REPOS = (
    RepoSpec(
        "live-bootstrap seed/steps",
        ".",
        paths=("seed", "steps"),
        exclude=("seed/stage0-posix",),
    ),
    RepoSpec("stage0-posix wrapper", "seed/stage0-posix"),
    RepoSpec("stage0-posix/x86", "seed/stage0-posix/x86"),
    RepoSpec("stage0-posix/AMD64", "seed/stage0-posix/AMD64"),
    RepoSpec("stage0-posix/AArch64", "seed/stage0-posix/AArch64"),
    RepoSpec("stage0-posix/riscv32", "seed/stage0-posix/riscv32"),
    RepoSpec("stage0-posix/riscv64", "seed/stage0-posix/riscv64"),
    RepoSpec("stage0-posix/armv7l", "seed/stage0-posix/armv7l"),
    RepoSpec("mescc-tools", "seed/stage0-posix/mescc-tools"),
    RepoSpec("mescc-tools-extra", "seed/stage0-posix/mescc-tools-extra"),
)


def git(repo: Path, *args: str) -> str:
    return subprocess.check_output(("git", "-C", str(repo), *args), text=True)


def short_head(repo: Path) -> str:
    return git(repo, "rev-parse", "--short", "HEAD").strip()


def diff_rows(spec: RepoSpec) -> list[Row]:
    repo = ROOT / spec.path
    args = ["diff", "--numstat", f"{spec.base}...HEAD"]
    if spec.paths:
        args.append("--")
        args.extend(spec.paths)
    out = git(repo, *args)
    rows = []
    for line in out.splitlines():
        if not line.strip():
            continue
        added, deleted, path = line.split("\t", 2)
        if path in spec.exclude:
            continue
        if added == "-" or deleted == "-":
            continue
        rows.append(Row(path=path, added=int(added), deleted=int(deleted)))
    return rows


def total(rows: list[Row]) -> tuple[int, int, int]:
    added = sum(row.added for row in rows)
    deleted = sum(row.deleted for row in rows)
    return added, deleted, added - deleted


def category(path: str) -> str:
    if path.endswith(".bake"):
        return "bake recipes"
    if path.endswith(".kaem") or "/simple-patches/" in path:
        return "kaem/simple-patch data removed"
    if path.startswith("Kaem/") or path == "docs/kaem.1":
        return "kaem implementation removed"
    if path == "bake.c":
        return "bake implementation"
    if path.endswith("simple-patch.c"):
        return "patch implementation"
    if "/patches/" in path or "/patches-pass1/" in path:
        return "unified patch files"
    if "kaem." in path or path == "kaem.run":
        return "launch files"
    if path.endswith(".checksums") or path.endswith(".answers"):
        return "checksums"
    if path.endswith(".c") or path.endswith(".h"):
        return "supporting C changes"
    if path.endswith(".md") or path.endswith(".rst"):
        return "documentation"
    return "other"


def markdown_table(headers: tuple[str, ...], rows: list[tuple[object, ...]]) -> str:
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(str(cell) for cell in row) + " |")
    return "\n".join(lines)


def format_signed(value: int) -> str:
    return f"{value:+d}"


def render() -> str:
    repo_rows: dict[str, list[Row]] = {}
    repo_meta: dict[str, tuple[str, str]] = {}
    for spec in REPOS:
        repo = ROOT / spec.path
        if not repo.exists():
            continue
        repo_rows[spec.name] = diff_rows(spec)
        repo_meta[spec.name] = (spec.path, short_head(repo))

    summary_rows = []
    grand_added = grand_deleted = 0
    for spec in REPOS:
        rows = repo_rows.get(spec.name)
        if rows is None:
            continue
        added, deleted, delta = total(rows)
        grand_added += added
        grand_deleted += deleted
        path, head = repo_meta[spec.name]
        summary_rows.append((spec.name, f"`{path}`", f"`{head}`", added, deleted, format_signed(delta)))

    grand_delta = grand_added - grand_deleted

    categories: dict[str, tuple[int, int]] = {}
    for rows in repo_rows.values():
        for row in rows:
            added, deleted = categories.get(category(row.path), (0, 0))
            categories[category(row.path)] = (added + row.added, deleted + row.deleted)
    category_rows = [
        (name, added, deleted, format_signed(added - deleted))
        for name, (added, deleted) in sorted(categories.items())
    ]

    lines = [
        "# LOC Audit",
        "",
        "This file is generated by `tools/loc_audit.py`. Re-run it after changing the bake or patch port:",
        "",
        "```sh",
        "python3 tools/loc_audit.py",
        "```",
        "",
        "## Scope",
        "",
        "The audit counts source lines that are materialized into the live-bootstrap root, not generated build output.",
        "`rootfs.py` copies the top-level `seed` and `steps` trees and the checked-out `seed/stage0-posix` tree into the target root.",
        "Because `stage0-posix` and its architecture/tool directories are git submodules, this report ignores parent gitlink rows and counts each checked-out source repository separately.",
        "",
        "The bake replacement boundary is the pre-bash build. Minimal kaem still runs the seed scripts that build bake itself.",
        "After bake exists, `kaem.*` launch files run `bootstrap.*.bake`, and generated `/steps/0.bake` builds through `bash-2.05b-pass1` before handing off to `bash /steps/1.sh`.",
        "Later packages are outside the kaem-to-bake replacement surface and are not needed to prove the LOC delta.",
        "",
        "## Counting Method",
        "",
        "The script uses `git diff --numstat origin/master...HEAD` in each materialized repo.",
        "For the top-level repo it restricts counting to `seed` and `steps`, and excludes the `seed/stage0-posix` gitlink because the submodule source is counted below.",
        "Binary rows are ignored. Renames are counted by Git's numstat additions and deletions.",
        "",
        "## Validation Boundary",
        "",
        "The focused validation target is:",
        "",
        "```sh",
        "nix develop .. -c ./rootfs.py --bwrap --external-sources --target target-bake-audit --mirror https://samuelt.me/pub/live-bootstrap",
        "```",
        "",
        "It is sufficient for the run to show:",
        "",
        "- `cc_x86` builds the early toolchain and `bake`.",
        "- `x86/bin/bake: OK` appears in the stage0 checksums.",
        "- `/steps/0.bake` builds through `bash-2.05b-pass1`.",
        "- `/steps/0.bake` reaches `bash /steps/1.sh`.",
        "",
        "A full rootfs build is still useful as a regression test for unified patch compatibility, but it is not required for the kaem/bake LOC measurement.",
        "",
        "## Summary",
        "",
        markdown_table(
            ("repo", "path", "head", "added", "deleted", "delta"),
            summary_rows,
        ),
        "",
        f"Materialized total: **{grand_added} added, {grand_deleted} deleted, {format_signed(grand_delta)} LOC**.",
        "",
        "## Contributions",
        "",
        markdown_table(
            ("area", "added", "deleted", "delta"),
            category_rows,
        ),
        "",
        "## Interpretation",
        "",
        "The biggest reductions come from deleting full kaem scripts and the old `mescc-tools/Kaem` implementation.",
        "The main additions are `bake.c`, bake recipes, the standard patch reader, and unified patch files that replace before/after simple-patch pairs.",
        "The relevant number is the materialized total above, because those are the sources copied into the bootstrap root and audited by the build.",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "-o",
        "--output",
        default="docs/loc_audit.md",
        help="markdown report path relative to the repository root",
    )
    args = parser.parse_args()
    output = ROOT / args.output
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render(), encoding="utf-8")


if __name__ == "__main__":
    main()
